version: '3.8' # This line can be removed as per the previous warning, but it's not the cause of this error.
services:
  db:
    image: mysql:8.0
    container_name: student-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234 
      MYSQL_DATABASE: student_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Scottyest04
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin: # This is at the same level of indentation as 'db'
    image: phpmyadmin/phpmyadmin
    container_name: student-phpmyadmin
    links:
      - db:db # This links the phpmyadmin service to the 'db' service
    environment:
      PMA_HOST: db # phpMyAdmin will connect to the 'db' service using its service name
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80" # Access phpMyAdmin on your host at http://localhost:8080

volumes: # This is at the root level of the file, not indented under any service
  db_data: